#!/usr/bin/env python
import configparser
import argparse
import pickle
import os
import shutil
import sys
import tempfile
import urllib.parse
from multiprocessing import cpu_count
import platform
import tagging
import transcode
import redactedapi
from _version import __version__
import html
import subprocess

def create_description(torrent, flac_dir, format, permalink):
    # Create an example command to document the transcode process.
    cmds = transcode.transcode_commands(format,
                                        transcode.needs_resampling(flac_dir),
                                        transcode.resample_rate(flac_dir),
            'input.flac', 'output' + transcode.encoders[format]['ext'])

    description = [
        'Transcode of [url=%s]%s[/url]' % (permalink, permalink),
        '',
        'Transcode process:',
        '',
        '[code]%s[/code]' % ' | '.join(cmds),
        '',
        'Created using [url=https://redacted.ch/forums.php?action=viewthread&threadid=35524]REDBetter (NullPointerNinja7 fork of iw00t fork)[/url]'
        ''
        ]
    return description

def formats_needed(group, torrent, supported_formats):
    same_group = lambda t: t['media'] == torrent['media'] and\
                           t['remasterYear'] == torrent['remasterYear'] and\
                           t['remasterTitle'] == torrent['remasterTitle'] and\
                           t['remasterRecordLabel'] == torrent['remasterRecordLabel'] and\
                           t['remasterCatalogueNumber'] == torrent['remasterCatalogueNumber']

    others = filter(same_group, group['torrents'])
    current_formats = set((t['format'], t['encoding']) for t in others)
    missing_formats = [format for format, details in [(f, redactedapi.formats[f]) for f in supported_formats]\
                           if (details['format'], details['encoding']) not in current_formats]
    allowed_formats = redactedapi.allowed_transcodes(torrent)
    return [format for format in missing_formats if format in allowed_formats]

def border_msg(msg):
    width = 0
    for line in msg.splitlines():
        length = len(line)
        if length > width:
            width = length

    dash = "-" * (width - 1)
    return "+{dash}+\n{msg}\n+{dash}+".format(dash=dash,msg=msg)

def main():
    default_config_dir = os.path.join(os.path.expanduser('~'), '.redactedbetter')
    default_config_path = os.path.join(default_config_dir, 'config')
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter, prog='redactedbetter')
    parser.add_argument('release_urls', nargs='*', help='the URL where the release is located')
    parser.add_argument('-s', '--single', action='store_true', help='only add one format per release (useful for getting unique groups)')
    parser.add_argument('-j', '--threads', type=int, help='number of threads to use when transcoding',
            default=max(cpu_count() - 1, 1))
    parser.add_argument('--config', help='the location of the configuration file', default=default_config_path)    
    parser.add_argument('--cache', help='the location of the cache', \
            default=os.path.normpath(os.path.expanduser('~/.redactedbetter/cache')))  # changed to make it cross platform compatible
    parser.add_argument('-U', '--no-upload', action='store_true', help='don\'t upload new torrents (in case you want to do it manually)')
    parser.add_argument('-Y', '--no-prompt', action='store_true', help='don\'t prompt user on every torrent')
    #parser.add_argument('-E', '--no-24bit-edit', action='store_true', help='don\'t try to edit 24-bit torrents mistakenly labeled as 16-bit')
    parser.add_argument('--version', action='version', version='%(prog)s ' + __version__)
    prompt_user = True

    args = parser.parse_args()

    config = configparser.RawConfigParser()
    try:
        open(args.config)
        config.read(args.config)
    except:
        if not os.path.exists(os.path.dirname(args.config)):
            os.makedirs(os.path.dirname(args.config))
        config.add_section('redacted')
        config.set('redacted', 'api_key', '')
        config.set('redacted', 'data_dir', '')
        config.set('redacted', 'output_dir', '')
        config.set('redacted', 'torrent_dir', '')
        config.set('redacted', 'formats', 'flac, v0, 320')
        config.set('redacted', 'media', ', '.join(redactedapi.lossless_media))
        #config.set('redacted', '24bit_behaviour','0')
        config.set('redacted', 'piece_length', '18')
        config.set('redacted', 'sonocop_app_path', '')
        config.write(open(args.config, 'w'))
        print(f'Please edit the configuration file: {args.config}')

        sys.exit(2)
    finally:
        api_key = config.get('redacted', 'api_key')
        sonocop_app_path =  config.get('redacted', 'sonocop_app_path')
        #password = config.get('redacted', 'password')
        try:
            session_cookie = os.path.expanduser(config.get('redacted', 'session_cookie'))
        except configparser.NoOptionError:
            session_cookie = None
        #do_24_bit = config.get('redacted', '24bit_behaviour')

        data_dir = os.path.expanduser(config.get('redacted', 'data_dir'))
        try:
            output_dir = os.path.expanduser(config.get('redacted', 'output_dir'))
        except configparser.NoOptionError:
            output_dir = None
        if not output_dir:
            output_dir = data_dir
        torrent_dir = os.path.expanduser(config.get('redacted', 'torrent_dir'))
        supported_formats = [format.strip().upper() for format in config.get('redacted', 'formats').split(',')]

        try:
            media_config = config.get('redacted', 'media')
            if not media_config:
                supported_media = redactedapi.lossless_media
            else:
                supported_media = set([medium.strip() for medium in media_config.split(',')])
                if not supported_media.issubset(set(redactedapi.lossless_media)):
                    print(f'Unsupported media type "{(supported_media - redactedapi.lossless_media).pop()}", edit your configuration')
                    print(f'Supported types are: {", ".join(redactedapi.lossless_media)}')
                    sys.exit(2)
        except configparser.NoOptionError:
            supported_media = redactedapi.lossless_media

    upload_torrent = not args.no_upload
    prompt_user = not args.no_prompt
    print ('Logging in to RED...')
    api = redactedapi.RedactedAPI(api_key)

    try:
        seen = pickle.load(open(args.cache, 'rb'))
    except FileNotFoundError:
        seen = set()
        pickle.dump(seen, open(args.cache, 'wb'))
    except Exception as err:
        print(f"Error loading cache {args.cache} : {err}")
        print(f"Try removing cachefile if created with earlier version of redbetter")
        raise err
    
    print ('Searching for transcode candidates...')
    if args.release_urls:
        print ('You supplied one or more release URLs, ignoring your configuration\'s media types.')
        candidates = [(int(query['id']), int(query['torrentid'])) for query in\
                [dict(urllib.parse.parse_qsl(urllib.parse.urlparse(url).query)) for url in args.release_urls]]
    else:
        candidates = api.snatched(skip=seen, media=supported_media)

    for groupid, torrentid in candidates:
        group = api.request_get('torrentgroup', id=groupid)
        if group != None:
            torrent = [t for t in group['torrents'] if t['id'] == torrentid][0]

            artist = "";
            name = html.unescape(group['group']['name'])
            if len(group['group']['musicInfo']['artists']) > 1:
                artist = "Various Artists"
            else:
                artist = group['group']['musicInfo']['artists'][0]['name']

            year = str(torrent['remasterYear'])
            if year == "0":
                year = str(group['group']['year'])

            releaseartist = "Release artist(s): %s" % artist
            releasename   = "Release name     : %s" % name
            releaseyear   = "Release year     : %s" % year
            releaseurl    = "Release URL      : %s" % api.release_url(group, torrent)

            # Concatenate as strings
            combined_str = releaseartist + "\n" + releasename + "\n" + releaseyear + "\n" + releaseurl

            print("\n\n")
            print(border_msg(combined_str))

            if not torrent['filePath']:
                flac_file = os.path.join(data_dir, html.unescape(torrent['fileList']).split('{{{')[0])
                if not os.path.exists(flac_file):
                    print(f"Path not found - skipping: {flac_file}")
                    continue
                flac_dir = os.path.join(data_dir, "%s (%s) [FLAC]" % (
                name, group['group']['year']))
                if not os.path.exists(flac_dir):
                    os.makedirs(flac_dir)
                shutil.copy(flac_file, flac_dir)
            else:
                flac_dir = os.path.join(data_dir, html.unescape(torrent['filePath']))

            # if int(do_24_bit):
            #     try:
            #         if transcode.is_24bit(flac_dir) and torrent['encoding'] != '24bit Lossless':
            #             # A lot of people are uploading FLACs from Bandcamp without realizing
            #             # that they're actually 24 bit files (usually 24/44.1). Since we know for
            #             # sure whether the files are 24 bit, we might as well correct the listing
            #             # on the site (and get an extra upload in the process).
            #             if args.no_24bit_edit:
            #                 print ("Release is actually 24-bit lossless, skipping.")
            #                 continue
            #             if int(do_24_bit) == 1:
            #                 confirmation = input("Mark release as 24bit lossless? y/n: ")
            #                 if confirmation != 'y':
            #                     continue
            #             print ("Marking release as 24bit lossless.")
            #           #  api.set_24bit(torrent)
            #             group = api.request_get('torrentgroup', id=groupid)
            #             torrent = [t for t in group['torrents'] if t['id'] == torrentid][0]
            #     except Exception as e:
            #         print(f"Error: can't edit 24-bit torrent - skipping: {e}")
            #         continue

            oktoprocess=True

            if (torrent["scene"] == True):
                print ("This is a scene torrent, cant recode without 'de-scening' it")
                oktoprocess=False
            
            if (torrent["remastered"] == False and torrent["remasterYear"] == 0):
                print ("This is an unconfirmed release - skipping")
                oktoprocess=False

            if (torrent["remastered"] == True and torrent["remasterYear"] == 0):
                print ("This is an unknown release - skipping")
                oktoprocess=False

            if (torrent["reported"] == True):
                print ("This torrent was reported - skipping")
                continue # recheck next time maybe it will not be reported

            if transcode.is_multichannel(flac_dir):
                print ("This is a multichannel release, which is unsupported - skipping")
                oktoprocess=False

            if (oktoprocess):
                needed = formats_needed(group, torrent, supported_formats)
                print(f"Formats needed: {', '.join(needed)}")

                if (len(needed) >0):
                    # Before proceeding, do the basic tag checks on the source
                    # files to ensure any uploads won't be reported, but punt
                    # on the tracknumber formatting; problems with tracknumber
                    # may be fixable when the tags are copied.
                    broken_tags = False
                    for flac_file in transcode.locate(flac_dir, transcode.ext_matcher('.flac')):
                        (ok, msg) = tagging.check_tags(flac_file, check_tracknumber_format=False)
                        if not ok:
                            print (f"A FLAC file in this release has unacceptable tags - skipping: {msg}")
                            print ("You might be able to trump it.")
                            broken_tags = True
                            break
                    if broken_tags:
                        continue

                    while os.path.exists(flac_dir) == False:
                        print (f"Path not found: {flac_dir}")
                        alternative_file_path_exists = ""
                        while (alternative_file_path_exists.lower() != "y") and (alternative_file_path_exists.lower() != "n"):
                            alternative_file_path_exists = input("Do you wish to provide an alternative file path? (y/n): ")

                        if alternative_file_path_exists.lower() == "y":
                            flac_dir = input("Alternative file path: ")
                        else:
                            print (f"Skipping: {flac_dir}")
                            break

                    if (torrent["lossyWebApproved"]): 
                        print (f"Lossy Web Approved, skipping transcoded flac check")
                    else:
                        if (torrent["lossyMasterApproved"]):
                            print (f"Lossy Master Approved, skipping transcoded flac check")
                        else:
                            transcode_count = 0
                            result=None
                            if (os.path.exists(sonocop_app_path)):
                                print (f"Checking if flac transcoded using sonocop")
                                # Run the command with the specified argument
                                result = subprocess.run([sonocop_app_path, flac_dir], check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
                                transcode_count = result.returncode
                            else:
                                try:
                                    # Attempt to run through docker
                                    command = ["docker", "run", "--rm", "-v", f'"{flac_dir}:/data"', "nullpointerninja7/sonocop:latest"]
                                    print("Sonocop not configured. Try to run it's docker container instead")
                                    print("Running command:", " ".join(command))
                                    result = subprocess.run(command, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
                                    transcode_count = result.returncode
                                except (subprocess.CalledProcessError, FileNotFoundError):
                                    # CalledProcessError if the command ran but failed
                                    # FileNotFoundError if the command was not found
                                    print (f"--Sonocop not configured in config file and docker launch failed. Cannot check transcodes, exiting.--")   
                                    sys.exit(99)
                                # Access the exit code
                            

                            # Optionally, print the standard output and standard error
                            print(result.stdout)
                            print(result.stderr)                    
                            if (transcode_count > 100):
                                print (f"***Possible system error *** Processing : {flac_dir}. Exiting.")
                                sys.exit(transcode_count)
                            if (transcode_count > 0):
                                print (f"***{transcode_count} transcoded flacs found *** Skipping : {flac_dir}")
                                print (f"***Manually review spectrograms and report this as a transcode if it is")
                                oktoprocess=False
                    if (oktoprocess):
                        for bitrate in needed:
                            if os.path.exists(flac_dir):
                                print (f'Adding format MP3 Bitrate {bitrate}')
                                tmpdir = tempfile.mkdtemp()
                                try:
                                    if len(torrent['remasterTitle']) >= 1:
                                        basename = artist + " - " + name + " (" + torrent['remasterTitle'] + ") " + "[" + year + "] (" + torrent['media'] + " - "
                                    else:
                                        basename = artist + " - " + name + " [" + year + "] (" + torrent['media'] + " - "

                                    transcode_dir = transcode.transcode_release(flac_dir, output_dir, basename, bitrate, max_threads=args.threads)
                                    if transcode_dir == False:
                                        print ("Skipping - some file(s) in this release were incorrectly marked as 24bit.")
                                        break

                                    new_torrent = transcode.make_torrent(transcode_dir, tmpdir, api.tracker, api.passkey, config.get('redacted', 'piece_length'))

                                    if upload_torrent:
                                        permalink = api.permalink(torrent)
                                        description = create_description(torrent, flac_dir, bitrate, permalink)
                                        api.upload(group, torrent, new_torrent, bitrate, description, prompt_user)

                                    if not os.path.exists(torrent_dir):
                                        os.makedirs(torrent_dir)
                                    shutil.copy(new_torrent, torrent_dir)
                                    print ("done!")
                                    if args.single: break
                                except Exception as e:
                                    print (f"Error adding format {bitrate}: {e}")
                                finally:
                                    shutil.rmtree(tmpdir)

            seen.add(torrentid)
            pickle.dump(seen, open(args.cache, 'wb'))

if __name__ == "__main__":
    main()
